# This the name of the workflow that will be displayed in Actions tab
name: CICD
# Manual click (dilver) workflow whenever user needs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: this the environment where this workflow runs
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:

# every jobs needs seperate runners, it is called parallelism 

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from GitHub"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container build"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the contianer 
        run: echo "Testing the contianer"
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name:  Depolying the app 
        run: echo "Docker compose deployed the app"
