# This workflow name
name: Hello workflow!
# run on an automatic tigger, when ever changes is pushed to branch deployment
on: 
  push: 
    branches: [main]

# These are jobs inside the workflows
jobs: 
# this is the name of the job
    greet:
      runs-on: ubuntu-latest
      steps:
        - name: say Hello to users 
          run: echo "Hello Dosto"
        - name: say Hello to username
          run: echo "Hello $USER"

    check_version:
      runs-on: ubuntu-latest
      steps:
        - name: show what is the version of python, docker, etc
          run: docker --version && python --version
    
